name: startup_auth_org_mobile
description: Mobile app (Flutter) for organization tasks
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter: { sdk: flutter }
  http: ^1.2.0
  flutter_hooks: ^0.20.5
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
dev_dependencies:
  flutter_test: { sdk: flutter }
flutter:
  uses-material-design: true